handlers:
  - sink: "sys.stdout"
    level: INFO
    format: "<green>{time}</green> - <level>{level}</level> - <cyan>{message}</cyan>"
  - sink: "file.log"
    level: DEBUG
    format: "{time} - {level} - {message}"
    rotation: "1 week"
    retention: "1 month"
    compression: "zip"
  - sink: "error.log"
    level: ERROR
    format: "{time} - {level} - {message}"
    rotation: "500 MB"
    retention: "10 days"
    compression: "gz"


extra:
  application: "MyApp"
  environment: "production"